spring.application.name=FeePortal

# Database Connection (MySQL)
# jdbc acts as a bridge between the application and the database, allowing us to connect to the MySQL database located at localhost on port 3306, with the database name fee_portal_db. The additional parameters ensure that the database is created if it doesn't exist, SSL is disabled for local development, and the server timezone is set to UTC to avoid timezone-related issues.
spring.datasource.url=jdbc:mysql://localhost:3306/fee_portal_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=darshana99
spring.datasource.password=password

# Hibernate Properties (Auto-create tables based on our Entities)
# what this does is just update the database schema based on the entities, it won't drop existing tables or data,or create new tables if they don't exist, it will just update the existing schema to match the entities, so it's a safe option for development and production environments.    
spring.jpa.hibernate.ddl-auto=update
# tis will print the generated SQL statements in the console, which can be helpful for debugging and understanding how Hibernate interacts with the database.
spring.jpa.show-sql=true
# this specifies the SQL dialect that Hibernate should use when generating SQL statements for MySQL. It ensures that the generated SQL is compatible with MySQL's syntax and features.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# this will format the generated SQL statements in a more readable way when they are printed in the console, making it easier to understand the structure of the SQL queries being executed.
spring.jpa.properties.hibernate.format_sql=true
